
<a class="btn btn-sm btn-default" href="<?php echo $this->url('Slider:Admin:Attribute@addAction', $id); ?>"><i class="glyphicon glyphicon-tag"></i> <?php $this->show('Add group'); ?></a>
<h4><i class="glyphicon glyphicon-book"></i> <?php $this->show('Groups'); ?></h4>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <td class="text-center">#</td>
                <td class="text-center"><?php $this->show('Name'); ?></td>
                <td class="text-center"><?php $this->show('Actions'); ?></td>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($groups as $group): ?>
            <tr>
                <td class="text-center text-muted"><?php echo $group->getId(); ?></td>
                <td class="text-center">
                    <a href="<?php echo $this->url('Slider:Admin:Attribute@groupAction', $group->getId()); ?>"><?php echo $group->getName(); ?></a>
                </td>
                <td class="text-center">
                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this group'); ?>" data-button="edit" href="<?php echo $this->url('Slider:Admin:Attribute@editAction', $group->getCategoryId(), $group->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this group'); ?>" data-button="delete" data-url="<?php echo $this->url('Slider:Admin:Attribute@deleteAction', $group->getCategoryId(), $group->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php if (empty($groups)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('This category has not attributes'); ?></h2>
    </div>
    <?php endif; ?>
</div>
