<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            isset($categoryId) ? $this->mapUrl('Slider:Admin:Image@addAction', array($categoryId), 1) : $this->url('Slider:Admin:Image@addAction') => 'Add a slider',
            'Slider:Admin:Category@addAction' => $extendedMode ? 'Add a category' : null
        ),

        'actions' => array(
            'data' => $images,
            'save' => 'Slider:Admin:Image@tweakAction',
            'delete' => 'Slider:Admin:Image@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Slider')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($images, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'image',
                        'value' => function($image){
                            return Element::image($image->getImageBag()->getUrl('400x200'), array('class' => 'img-fluid'));
                        }
                    ),

                    array(
                        'column' => 'category_name',
                        'label' => 'Category'
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($image){
                            return Element::checkbox(sprintf('published[%s]', $image->getId()), $image->getPublished());
                        }
                    ),
                    
                    array(
                        'column' => 'order',
                        'value' => function($image){
                            return Element::number(sprintf('order[%s]', $image->getId()), $image->getOrder(), array('class' => 'form-control', 'min' => '0'));
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($image){
                        return Icon::edit(
                            $this->url('Slider:Admin:Image@editAction', $image->getId()),
                            $this->translate('Edit this image')
                        );
                    },

                    'remove' => function($image){
                        return Icon::remove(
                            $this->url('Slider:Admin:Image@deleteAction', $image->getId()),
                            $this->translate('Remove this image')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($images)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No images'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>
</div>

<div class="card">
    <div class="table-responsive">
        <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

        <?= $this->widget(new GridViewWidget($categories, array(
            'tableClass' => 'table table-hover table-bordered table-striped',
            'rowAttributes' => array(
                'class' => function($category) use ($categoryId){
                    return $categoryId == $category->getId() ? 'table-info' : null;
                }
            ),
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                    'value' => function($category){
                        return Element::link($category->getName(), $this->url('Slider:Admin:Browser@categoryAction', $category->getId()));
                    }
                ),

                array(
                    'column' => 'slides_count',
                    'label' => 'Amount of slides'
                ),
                
                array(
                    'column' => 'height'
                ),

                array(
                    'column' => 'width'
                ),

                array(
                    'column' => 'class',
                    'hidden' => !$extendedMode
                ),
            ),

            'actions' => !$extendedMode ? array() : array(
                'manage' => function($category){
                    return Icon::details(
                        $this->url('Slider:Admin:Attribute@listAction', $category->getId()),
                        $this->translate('Manage attributes')
                    );
                },

                'edit' => function($category){
                    return Icon::edit(
                        $this->url('Slider:Admin:Category@editAction', $category->getId()),
                        $this->translate('Edit this category')
                    );
                },

                'remove' => function($category){
                    return Icon::remove(
                        $this->url('Slider:Admin:Category@deleteAction', $category->getId()),
                        $this->translate('Remove this category')
                    );
                }
            )
        ))); ?>

        <?php if (empty($categories)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
        </div>
        <?php endif; ?>
    </div>
</div>
