<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', [
        'items' => [
            isset($categoryId) ? $this->mapUrl('Slider:Admin:Image@addAction', [$categoryId], 1) : $this->url('Slider:Admin:Image@addAction') => 'Add a slider',
            'Slider:Admin:Category@addAction' => $extendedMode ? 'Add a category' : null
        ],

        'actions' => [
            'data' => $images,
            'save' => 'Slider:Admin:Image@tweakAction',
            'delete' => 'Slider:Admin:Image@deleteAction'
        ]
    ]); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Slider')); ?>

    <form>
        <?php $this->loadPartial('grid', [
            'rows' => $images,
            'pagination' => true,
            'grid' => [
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'image',
                        'value' => function($image){
                            return Element::image($image->getImageBag()->getUrl('400x200'), array('class' => 'img-fluid'));
                        }
                    ],

                    [
                        'column' => 'category_name',
                        'label' => 'Category'
                    ],

                    [
                        'column' => 'published',
                        'value' => function($image){
                            return Element::checkbox(sprintf('published[%s]', $image->getId()), $image->getPublished());
                        }
                    ],

                    [
                        'column' => 'order',
                        'value' => function($image){
                            return Element::number(sprintf('order[%s]', $image->getId()), $image->getOrder(), ['class' => 'form-control', 'min' => '0']);
                        }
                    ]
                ],

                'actions' => [
                    function($image){
                        return Icon::edit(
                            $this->url('Slider:Admin:Image@editAction', $image->getId()),
                            $this->translate('Edit this image')
                        );
                    },

                    function($image){
                        return Icon::remove(
                            $this->url('Slider:Admin:Image@deleteAction', $image->getId()),
                            $this->translate('Remove this image')
                        );
                    }
                ]
            ]
        ]); ?>
    </form>
</div>

<div class="card">
    <?php $this->loadPartial('grid', [
        'title' => 'Categories',
        'rows' => $categories,
        'grid' => [
            'tableClass' => 'table table-hover table-bordered table-striped',
            'rowAttributes' => [
                'class' => function($category) use ($categoryId){
                    return $categoryId == $category->getId() ? 'table-info' : null;
                }
            ],
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'name',
                    'attributes' => [
                        'class' => null
                    ],
                    'value' => function($category){
                        return Element::link($category->getName(), $this->url('Slider:Admin:Browser@categoryAction', $category->getId()));
                    }
                ],

                [
                    'column' => 'slides_count',
                    'label' => 'Amount of slides'
                ],

                [
                    'column' => 'height'
                ],

                [
                    'column' => 'width'
                ],

                [
                    'column' => 'class',
                    'hidden' => !$extendedMode
                ]
            ],

            'actions' => !$extendedMode ? [] : [
                function($category){
                    return Icon::details(
                        $this->url('Slider:Admin:Attribute@listAction', $category->getId()),
                        $this->translate('Manage attributes')
                    );
                },

                function($category){
                    return Icon::edit(
                        $this->url('Slider:Admin:Category@editAction', $category->getId()),
                        $this->translate('Edit this category')
                    );
                },

                function($category){
                    return Icon::remove(
                        $this->url('Slider:Admin:Category@deleteAction', $category->getId()),
                        $this->translate('Remove this category')
                    );
                }
            ]
        ]
    ]); ?>
</div>