<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<form data-group="category">
	<div class="well">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('category[class]', $category->getClass(), array('class' => 'form-control', 'placeholder' => $this->translate('Class to simplify rendering'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Width'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
					<?php echo Element::number('category[width]', $category->getWidth(), array('class' => 'form-control', 'placeholder' => $this->translate('Desired width for slide images'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Height'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::number('category[height]', $category->getHeight(), array('class' => 'form-control', 'placeholder' => $this->translate('Desired height for slide images'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
	</div>
	
	<?php if (!$category->getId()): ?>
	<button data-button="add" data-back-url="<?php echo $this->url('Slider:Admin:Category@editAction', null); ?>" data-url="<?php echo $this->url('Slider:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	
	<?php else: ?>
	<button data-button="save" data-url="<?php echo $this->url('Slider:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	
	<?php endif; ?>
	<button data-button="cancel" data-url="<?php echo $this->url('Slider:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
