<?php

use Krystal\Form\Element;

?>

<?php if (!empty($categories)): ?>

<form data-group="image">

	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#image" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Image'); ?></a></li>
		<li role="presentation"><a href="#options" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Options'); ?></a></li>
	</ul>
	
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane fade in active" id="image" role="tabpanel">
			<div class="well clearfix">
				
                <?php echo Element::hidden('image[id]', $image->getId()); ?>
                <?php echo Element::hidden('image[image]', $image->getCover()); ?>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::text('image[name]', $image->getName(), array('class' => 'form-control', 'placeholder' => $this->translate("Slider's name. When empty, then is taken from a filename"))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
					<div class="col-lg-10">
                        <?php echo Element::select('image[category_id]', $categories, $image->getCategoryId(), array('class' => 'form-control')); ?>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
					<div class="col-lg-10">
						
						<?php if ($image->getCover() != ''): ?>
						<img class="img-responsive" src="<?php echo $image->getImageBag()->getUrl('400x200'); ?>" />
						
						<?php else: ?>
						<img data-image="preview" />
						
						<?php endif; ?>
						
						<br />
						<br />
						
                        <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg'); ?>
					</div>
				</div>
			</div>
		</div>
		
		<div class="tab-pane" id="options" role="tabpanel">
			<div class="well">
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::number('image[order]', $image->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Image sort order'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::textarea('image[description]', $image->getDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Image description'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Link'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::text('image[link]', $image->getLink(), array('class' => 'form-control', 'placeholder' => $this->translate('Link to be opened when clicking on the slider'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group clearfix">
					<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
					<div class="col-lg-10">
                        <?php echo Element::checkbox('image[published]', $image->getPublished(), array('class' => 'form-control')); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<?php if (!$image->getId()): ?>
	
    <button data-button="add" data-back-url="<?php echo $this->url('Slider:Admin:Image:Edit@indexAction', null); ?>" data-url="<?php echo $this->url('Slider:Admin:Image:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Slider:Admin:Image:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Upload new'); ?></button>
    
    <?php else: ?>
	
	<button data-button="save" data-url="<?php echo $this->url('Slider:Admin:Image:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Slider:Admin:Image:Add@indexAction'); ?>" data-url="<?php echo $this->url('Slider:Admin:Image:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Upload new'); ?></button>
	
    <?php endif; ?>
	
	<button data-button="cancel" data-url="<?php echo $this->url('Slider:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>

<?php else: ?>

<div class="well">
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('In order to upload a slider, you need to create at least one category'); ?></h2>
	</div>
</div>

<?php endif; ?>
