<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<?php if (!empty($categories)): ?>

<form data-group="image">

	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#image" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Image'); ?></a></li>
		<li role="presentation"><a href="#options" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Options'); ?></a></li>
        
        <?php if ($hasAttributes): ?>
		<li role="presentation"><a href="#attrs" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Attributes'); ?></a></li>
        <?php endif; ?>
	</ul>
	
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane fade in active" id="image" role="tabpanel">
			<div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $image); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate("Slider's name. When empty, then is taken from a filename"))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Image description'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Link'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][link]', $language->getId()), $entity->getLink(), array('class' => 'form-control', 'placeholder' => $this->translate('Link to be opened when clicking on the slider'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
			</div>
		</div>

        <div class="tab-pane" id="options" role="tabpanel">
            <?php echo Element::hidden('image[id]', $entity->getId()); ?>
            <?php echo Element::hidden('image[image]', $entity->getCover()); ?>

			<div class="well">
				<div class="form-group">
					<label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
					<div class="col-lg-10">
                        <?php echo Element::select('image[category_id]', $categories, $entity->getCategoryId(), array('class' => 'form-control')); ?>
					</div>
				</div>

				<div class="form-group">
					<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
					<div class="col-lg-10">
						<div class="input-group">
                            <?php echo Element::number('image[order]', $entity->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Image sort order'))); ?>
							<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
						</div>
					</div>
				</div>
				
				<div class="form-group">
					<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
					<div class="col-lg-10">
                        <?php echo Element::checkbox('image[published]', $entity->getPublished(), array('class' => 'form-control')); ?>
					</div>
				</div>

				<div class="form-group">
					<label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
					<div class="col-lg-10">

						<?php if ($entity->getCover() != ''): ?>
                        <p><img class="img-responsive" src="<?php echo $entity->getImageBag()->getUrl('400x200'); ?>" /></p>
						<?php else: ?>
                        <p><img data-image="preview" /></p>

						<?php endif; ?>

                        <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                        <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
					</div>
				</div>
			</div>
        </div>

        <?php if ($hasAttributes): ?>
		<div class="tab-pane" id="attrs" role="tabpanel">
            <div class="well">
                <?php foreach ($attributes as $attribute): ?>
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php echo $attribute->getName(); ; ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text(sprintf('image[attributes][%s]', $attribute->getId()), $attribute->getValue(), array('class' => 'form-control')); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>
	</div>

	<?php if ($new): ?>

    <button data-button="add" data-back-url="<?php echo $this->url('Slider:Admin:Image@editAction', null); ?>" data-url="<?php echo $this->url('Slider:Admin:Image@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Slider:Admin:Image@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Upload new'); ?></button>

    <?php else: ?>

	<button data-button="save" data-url="<?php echo $this->url('Slider:Admin:Image@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Slider:Admin:Image@addAction'); ?>" data-url="<?php echo $this->url('Slider:Admin:Image@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Upload new'); ?></button>

    <?php endif; ?>

	<button data-button="cancel" data-url="<?php echo $this->url('Slider:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>

<?php else: ?>

<div class="well">
	<div class="center-block">
		<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('In order to upload a slider, you need to create at least one category'); ?></h2>
	</div>
</div>

<?php endif; ?>
